<a href="https://colab.research.google.com/github/backblaz/DataScience-Exercise/blob/main/Sesi_3_NumPY_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### NumPy Introduction ##

In [ ]:
import numpy as np

Membuat Array

In [ ]:
np.array(0)

array(0)

In [ ]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [ ]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [ ]:
print(np.arange(4))
print(np.arange(0,10,2))
print(np.arange(3,34,5))

[0 1 2 3]
[0 2 4 6 8]
[ 3  8 13 18 23 28 33]


Index dan slicing

In [ ]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[0:2])
print(data[1:])

[1 2 3]
1
[1 2]
[2 3]


More Array Operations

In [ ]:
data.max()
data.min()
data.sum()

In [ ]:
from numpy import random


In [ ]:
x = random.randint(30, size=(3, 5))
print(x)

[[12  7  9 10 12]
 [25  7 19 26  9]
 [15 12 10  3 23]]


In [ ]:
x.sum()

199

In [ ]:
x.min()

3

In [ ]:
x.min(axis=0)

array([12,  7,  9,  3,  9])

In [ ]:
x.max()

26

In [ ]:
x.mean()

13.266666666666667

In [ ]:
x.std()

6.7178038739523265